include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps_sub/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
obj-y	+=  ltr553_sub.o


